# Copyright 2022-2023 ETH Zurich and the Daisytuner authors.
from daisytuner.passes.data_dependent_symbol_analysis import DataDependentSymbolAnalysis
from daisytuner.passes.dataflow_maximization import DataflowMaximization
from daisytuner.passes.indirection_propagation import IndirectionPropagation
from daisytuner.passes.map_compact_form import MapCompactForm
from daisytuner.passes.map_inlining import MapInlining
from daisytuner.passes.map_expanded_form import MapExpandedForm
from daisytuner.passes.map_to_loop import MapToLoop
from daisytuner.passes.maximal_map_fission import MaximalMapFission
from daisytuner.passes.stride_minimization import StrideMinimization
